# Generated by Django 3.1.7 on 2021-03-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_tweet_parent'),
        ('tweets', '0002_auto_20210303_1123'),
    ]

    operations = [
    ]
